#
# Copyright (c) 2024 General Motors GTO LLC.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Public License v2.
#
# SPDX-FileType: DOCUMENTATION
# SPDX-FileCopyrightText: 2023 General Motors GTO LLC
# SPDX-License-Identifier: Apache-2.0
#
[versions]
android = "8.2.+"
android-material = "1.6.+"
androidx-junit = "1.1.5"
androidx-ktx = "1.6.0"
junit = "4.13.2"
kotlin = "1.9.21"
kotlinx-coroutines = "1.7.1"
ksp = "1.9.21-1.0.15"
mockito = "4.6.1"
robolectric = "4.7.3"
room = "2.4.2"
up-client-android-java = "0.1.+"
up-java = "0.1.9"

[libraries]
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit"}
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-ktx" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-stdlib = { module =  "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
up-client-android-java = { module = "org.eclipse.uprotocol:up-client-android-java", version.ref = "up-client-android-java" }
up-java = { module = "org.eclipse.uprotocol:up-java", version.ref = "up-java" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
